name: Remote Bench

on: push

jobs:
  submit:
    runs-on: ubuntu-latest
    outputs:
      benchid: ${{ steps.submit.outputs.benchid }}
    steps:
      - id: submit
        name: Submit
        run: |
          echo "${{ secrets.BENCH_KEY }}" > bench-key
          chmod 600 bench-key
          BENCHID=$(ssh -i bench-key -o StrictHostKeyChecking=no -o LogLevel=error \
              ${{ secrets.BENCH_HOST }} http://github.com/${{ github.repository }}.git \
              $GITHUB_SHA coq-tactician-stdlib.8.14.dev \"\" \"Set Tactician Benchmark 40.\")
          echo $BENCHID
          echo "::set-output name=benchid::$BENCHID"
  attach0:
    runs-on: ubuntu-latest
    needs: [submit]
    outputs:
      finished: ${{ steps.attach.outputs.finished }}
    
    steps:
      - id: attach
        name: Attach
        run: |
          echo "${{ needs.submit.outputs.benchid }}"
          echo "${{ secrets.ATTACH_KEY }}" > attach-key
          chmod 600 attach-key
          set -o pipefail
          set +e
          timeout 355m ssh -tt -i attach-key -o StrictHostKeyChecking=no -o LogLevel=error \
                  ${{ secrets.BENCH_HOST }} ${{ needs.submit.outputs.benchid }}
          EXIT=$?
          echo "Exit code $EXIT"
          if [ $EXIT -eq 124 ]; then
              echo "::set-output name=finished::false"
              echo "Job did not finish before Github time limit, spilling to next step"
          else
              exit $EXIT
          fi
  attach1:
    runs-on: ubuntu-latest
    needs: [submit, attach0]
    outputs:
      finished: ${{ steps.attach.outputs.finished }}
    if: ${{ needs.attach0.outputs.finished == 'false' }}
    steps:
      - id: attach
        name: Attach
        run: |
          echo "${{ needs.submit.outputs.benchid }}"
          echo "${{ secrets.ATTACH_KEY }}" > attach-key
          chmod 600 attach-key
          set -o pipefail
          set +e
          timeout 355m ssh -tt -i attach-key -o StrictHostKeyChecking=no -o LogLevel=error \
                  ${{ secrets.BENCH_HOST }} ${{ needs.submit.outputs.benchid }}
          EXIT=$?
          echo "Exit code $EXIT"
          if [ $EXIT -eq 124 ]; then
              echo "::set-output name=finished::false"
              echo "Job did not finish before Github time limit, spilling to next step"
          else
              exit $EXIT
          fi
  attach2:
    runs-on: ubuntu-latest
    needs: [submit, attach1]
    outputs:
      finished: ${{ steps.attach.outputs.finished }}
    if: ${{ needs.attach1.outputs.finished == 'false' }}
    steps:
      - id: attach
        name: Attach
        run: |
          echo "${{ needs.submit.outputs.benchid }}"
          echo "${{ secrets.ATTACH_KEY }}" > attach-key
          chmod 600 attach-key
          set -o pipefail
          set +e
          timeout 355m ssh -tt -i attach-key -o StrictHostKeyChecking=no -o LogLevel=error \
                  ${{ secrets.BENCH_HOST }} ${{ needs.submit.outputs.benchid }}
          EXIT=$?
          echo "Exit code $EXIT"
          if [ $EXIT -eq 124 ]; then
              echo "::set-output name=finished::false"
              echo "Job did not finish before Github time limit, spilling to next step"
          else
              exit $EXIT
          fi
  attach3:
    runs-on: ubuntu-latest
    needs: [submit, attach2]
    outputs:
      finished: ${{ steps.attach.outputs.finished }}
    if: ${{ needs.attach2.outputs.finished == 'false' }}
    steps:
      - id: attach
        name: Attach
        run: |
          echo "${{ needs.submit.outputs.benchid }}"
          echo "${{ secrets.ATTACH_KEY }}" > attach-key
          chmod 600 attach-key
          set -o pipefail
          set +e
          timeout 355m ssh -tt -i attach-key -o StrictHostKeyChecking=no -o LogLevel=error \
                  ${{ secrets.BENCH_HOST }} ${{ needs.submit.outputs.benchid }}
          EXIT=$?
          echo "Exit code $EXIT"
          if [ $EXIT -eq 124 ]; then
              echo "::set-output name=finished::false"
              echo "Job did not finish before Github time limit, spilling to next step"
          else
              exit $EXIT
          fi
  attach4:
    runs-on: ubuntu-latest
    needs: [submit, attach3]
    outputs:
      finished: ${{ steps.attach.outputs.finished }}
    if: ${{ needs.attach3.outputs.finished == 'false' }}
    steps:
      - id: attach
        name: Attach
        run: |
          echo "${{ needs.submit.outputs.benchid }}"
          echo "${{ secrets.ATTACH_KEY }}" > attach-key
          chmod 600 attach-key
          set -o pipefail
          set +e
          timeout 355m ssh -tt -i attach-key -o StrictHostKeyChecking=no -o LogLevel=error \
                  ${{ secrets.BENCH_HOST }} ${{ needs.submit.outputs.benchid }}
          EXIT=$?
          echo "Exit code $EXIT"
          if [ $EXIT -eq 124 ]; then
              echo "::set-output name=finished::false"
              echo "Job did not finish before Github time limit, spilling to next step"
          else
              exit $EXIT
          fi
  attach5:
    runs-on: ubuntu-latest
    needs: [submit, attach4]
    outputs:
      finished: ${{ steps.attach.outputs.finished }}
    if: ${{ needs.attach4.outputs.finished == 'false' }}
    steps:
      - id: attach
        name: Attach
        run: |
          echo "${{ needs.submit.outputs.benchid }}"
          echo "${{ secrets.ATTACH_KEY }}" > attach-key
          chmod 600 attach-key
          set -o pipefail
          set +e
          timeout 355m ssh -tt -i attach-key -o StrictHostKeyChecking=no -o LogLevel=error \
                  ${{ secrets.BENCH_HOST }} ${{ needs.submit.outputs.benchid }}
          EXIT=$?
          echo "Exit code $EXIT"
          if [ $EXIT -eq 124 ]; then
              echo "::set-output name=finished::false"
              echo "Job did not finish before Github time limit, spilling to next step"
          else
              exit $EXIT
          fi
  attach6:
    runs-on: ubuntu-latest
    needs: [submit, attach5]
    outputs:
      finished: ${{ steps.attach.outputs.finished }}
    if: ${{ needs.attach5.outputs.finished == 'false' }}
    steps:
      - id: attach
        name: Attach
        run: |
          echo "${{ needs.submit.outputs.benchid }}"
          echo "${{ secrets.ATTACH_KEY }}" > attach-key
          chmod 600 attach-key
          set -o pipefail
          set +e
          timeout 355m ssh -tt -i attach-key -o StrictHostKeyChecking=no -o LogLevel=error \
                  ${{ secrets.BENCH_HOST }} ${{ needs.submit.outputs.benchid }}
          EXIT=$?
          echo "Exit code $EXIT"
          if [ $EXIT -eq 124 ]; then
              echo "::set-output name=finished::false"
              echo "Job did not finish before Github time limit, spilling to next step"
          else
              exit $EXIT
          fi
  attach7:
    runs-on: ubuntu-latest
    needs: [submit, attach6]
    outputs:
      finished: ${{ steps.attach.outputs.finished }}
    if: ${{ needs.attach6.outputs.finished == 'false' }}
    steps:
      - id: attach
        name: Attach
        run: |
          echo "${{ needs.submit.outputs.benchid }}"
          echo "${{ secrets.ATTACH_KEY }}" > attach-key
          chmod 600 attach-key
          set -o pipefail
          set +e
          timeout 355m ssh -tt -i attach-key -o StrictHostKeyChecking=no -o LogLevel=error \
                  ${{ secrets.BENCH_HOST }} ${{ needs.submit.outputs.benchid }}
          EXIT=$?
          echo "Exit code $EXIT"
          if [ $EXIT -eq 124 ]; then
              echo "::set-output name=finished::false"
              echo "Job did not finish before Github time limit, spilling to next step"
          else
              exit $EXIT
          fi
  attach8:
    runs-on: ubuntu-latest
    needs: [submit, attach7]
    outputs:
      finished: ${{ steps.attach.outputs.finished }}
    if: ${{ needs.attach7.outputs.finished == 'false' }}
    steps:
      - id: attach
        name: Attach
        run: |
          echo "${{ needs.submit.outputs.benchid }}"
          echo "${{ secrets.ATTACH_KEY }}" > attach-key
          chmod 600 attach-key
          set -o pipefail
          set +e
          timeout 355m ssh -tt -i attach-key -o StrictHostKeyChecking=no -o LogLevel=error \
                  ${{ secrets.BENCH_HOST }} ${{ needs.submit.outputs.benchid }}
          EXIT=$?
          echo "Exit code $EXIT"
          if [ $EXIT -eq 124 ]; then
              echo "::set-output name=finished::false"
              echo "Job did not finish before Github time limit, spilling to next step"
          else
              exit $EXIT
          fi
  attach9:
    runs-on: ubuntu-latest
    needs: [submit, attach8]
    outputs:
      finished: ${{ steps.attach.outputs.finished }}
    if: ${{ needs.attach8.outputs.finished == 'false' }}
    steps:
      - id: attach
        name: Attach
        run: |
          echo "${{ needs.submit.outputs.benchid }}"
          echo "${{ secrets.ATTACH_KEY }}" > attach-key
          chmod 600 attach-key
          set -o pipefail
          set +e
          timeout 355m ssh -tt -i attach-key -o StrictHostKeyChecking=no -o LogLevel=error \
                  ${{ secrets.BENCH_HOST }} ${{ needs.submit.outputs.benchid }}
          EXIT=$?
          echo "Exit code $EXIT"
          if [ $EXIT -eq 124 ]; then
              echo "::set-output name=finished::false"
              echo "Job did not finish before Github time limit, spilling to next step"
          else
              exit $EXIT
          fi
  attach10:
    runs-on: ubuntu-latest
    needs: [submit, attach9]
    outputs:
      finished: ${{ steps.attach.outputs.finished }}
    if: ${{ needs.attach9.outputs.finished == 'false' }}
    steps:
      - id: attach
        name: Attach
        run: |
          echo "${{ needs.submit.outputs.benchid }}"
          echo "${{ secrets.ATTACH_KEY }}" > attach-key
          chmod 600 attach-key
          set -o pipefail
          set +e
          timeout 355m ssh -tt -i attach-key -o StrictHostKeyChecking=no -o LogLevel=error \
                  ${{ secrets.BENCH_HOST }} ${{ needs.submit.outputs.benchid }}
          EXIT=$?
          echo "Exit code $EXIT"
          if [ $EXIT -eq 124 ]; then
              echo "::set-output name=finished::false"
              echo "Job did not finish before Github time limit, spilling to next step"
          else
              exit $EXIT
          fi
  attach11:
    runs-on: ubuntu-latest
    needs: [submit, attach10]
    outputs:
      finished: ${{ steps.attach.outputs.finished }}
    if: ${{ needs.attach10.outputs.finished == 'false' }}
    steps:
      - id: attach
        name: Attach
        run: |
          echo "${{ needs.submit.outputs.benchid }}"
          echo "${{ secrets.ATTACH_KEY }}" > attach-key
          chmod 600 attach-key
          set -o pipefail
          set +e
          timeout 355m ssh -tt -i attach-key -o StrictHostKeyChecking=no -o LogLevel=error \
                  ${{ secrets.BENCH_HOST }} ${{ needs.submit.outputs.benchid }}
          EXIT=$?
          echo "Exit code $EXIT"
          if [ $EXIT -eq 124 ]; then
              echo "::set-output name=finished::false"
              echo "Job did not finish before Github time limit, spilling to next step"
          else
              exit $EXIT
          fi
  attach12:
    runs-on: ubuntu-latest
    needs: [submit, attach11]
    outputs:
      finished: ${{ steps.attach.outputs.finished }}
    if: ${{ needs.attach11.outputs.finished == 'false' }}
    steps:
      - id: attach
        name: Attach
        run: |
          echo "${{ needs.submit.outputs.benchid }}"
          echo "${{ secrets.ATTACH_KEY }}" > attach-key
          chmod 600 attach-key
          set -o pipefail
          set +e
          timeout 355m ssh -tt -i attach-key -o StrictHostKeyChecking=no -o LogLevel=error \
                  ${{ secrets.BENCH_HOST }} ${{ needs.submit.outputs.benchid }}
          EXIT=$?
          echo "Exit code $EXIT"
          if [ $EXIT -eq 124 ]; then
              echo "::set-output name=finished::false"
              echo "Job did not finish before Github time limit, spilling to next step"
          else
              exit $EXIT
          fi
  attach13:
    runs-on: ubuntu-latest
    needs: [submit, attach12]
    outputs:
      finished: ${{ steps.attach.outputs.finished }}
    if: ${{ needs.attach12.outputs.finished == 'false' }}
    steps:
      - id: attach
        name: Attach
        run: |
          echo "${{ needs.submit.outputs.benchid }}"
          echo "${{ secrets.ATTACH_KEY }}" > attach-key
          chmod 600 attach-key
          set -o pipefail
          set +e
          timeout 355m ssh -tt -i attach-key -o StrictHostKeyChecking=no -o LogLevel=error \
                  ${{ secrets.BENCH_HOST }} ${{ needs.submit.outputs.benchid }}
          EXIT=$?
          echo "Exit code $EXIT"
          if [ $EXIT -eq 124 ]; then
              echo "::set-output name=finished::false"
              echo "Job did not finish before Github time limit, spilling to next step"
          else
              exit $EXIT
          fi
