name: Stdlib

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          path: 'coq-tactician'
      - uses: actions/checkout@v2
        with:
          repository: 'coq-tactician/coq-tactician-stdlib'
          ref: 'coq8.14'
          path: 'coq-tactician-stdlib'
      - uses: coq-community/docker-coq-action@v1.2.3
        with:
          opam_file: 'coq-tactician.opam'
          coq_version: '8.14'
          ocaml_version: '4.12-flambda'
          install: |
            startGroup "Install dependencies"
              opam repo add coq-extra-dev https://coq.inria.fr/opam/extra-dev
              opam pin add -n -y -k path coq-tactician coq-tactician/
              opam update -y
              opam install -y -j 2 coq-tactician
            endGroup
          script: |
            startGroup "Build"
              sudo chmod -R 777 .
              opam exec -- make -C coq-tactician-stdlib -j2
            endGroup
          uninstall: |
            startGroup "Uninstallation test"
              opam remove coq-tactician
            endGroup
