name: Stdlib Daily

on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - branch: coq8.10
            coq_version: '8.10'
            ocaml_version: 4.09-flambda
          - branch: coq8.11
            coq_version: 8.11
            ocaml_version: 4.11-flambda
          - branch: coq8.12
            coq_version: 8.12
            ocaml_version: 4.11-flambda
          - branch: coq8.13
            coq_version: 8.13
            ocaml_version: 4.12-flambda
          - branch: coq8.14
            coq_version: 8.14
            ocaml_version: 4.12-flambda
          - branch: coq8.15
            coq_version: 8.15
            ocaml_version: 4.12-flambda
          - branch: coqdev
            coq_version: dev
            ocaml_version: 4.12-flambda

    steps:
      - uses: actions/checkout@v2
        with:
          path: 'coq-tactician'
          ref: ${{ matrix.branch }}
      - uses: actions/checkout@v2
        with:
          repository: 'coq-tactician/coq-tactician-stdlib'
          ref: ${{ matrix.branch }}
          path: 'coq-tactician-stdlib'
      - uses: coq-community/docker-coq-action@v1.2.3
        with:
          opam_file: 'coq-tactician.opam'
          coq_version: ${{ matrix.coq_version }}
          ocaml_version: ${{ matrix.ocaml_version }}
          install: |
            startGroup "Install dependencies"
              opam repo add coq-extra-dev https://coq.inria.fr/opam/extra-dev
              opam pin add -n -y -k path coq-tactician coq-tactician/
              opam update -y
              opam install -y -j 2 coq-tactician
            endGroup
          script: |
            startGroup "Build"
              sudo chmod -R 777 .
              opam exec -- make -C coq-tactician-stdlib -j2
            endGroup
          uninstall: |
            startGroup "Uninstallation test"
              opam remove coq-tactician
            endGroup
